// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4vIhAGUhtqJVyTyXGLoN1fjUyEOpfgPM',
    appId: '1:847264029141:web:f8a71c165f71388b11055c',
    messagingSenderId: '847264029141',
    projectId: 'flutter-projects-27ad3',
    authDomain: 'flutter-projects-27ad3.firebaseapp.com',
    storageBucket: 'flutter-projects-27ad3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFoVwKvtYwgCMyjSxTziwHFwOBE_yWHP4',
    appId: '1:847264029141:android:a87b30b44d0aca1211055c',
    messagingSenderId: '847264029141',
    projectId: 'flutter-projects-27ad3',
    storageBucket: 'flutter-projects-27ad3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzqhq5CHMtHawATsie0thVX2hEiPevWPA',
    appId: '1:847264029141:ios:95e8f68c9dd9068611055c',
    messagingSenderId: '847264029141',
    projectId: 'flutter-projects-27ad3',
    storageBucket: 'flutter-projects-27ad3.appspot.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzqhq5CHMtHawATsie0thVX2hEiPevWPA',
    appId: '1:847264029141:ios:9434cab8ea5d58cb11055c',
    messagingSenderId: '847264029141',
    projectId: 'flutter-projects-27ad3',
    storageBucket: 'flutter-projects-27ad3.appspot.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
